language: dart

dart:
  - stable
  - dev

install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=./flutter/bin:$PATH
  - flutter doctor

script:
  - flutter packages get
  - flutter analyze --no-pub --no-current-package lib/ test/
  - flutter test --no-pub test/

cache:
  directories:
  - "$HOME/.pub-cache"