// Mocks generated by Mockito 5.0.5 from annotations
// in parse_server_sdk/test/parse_query_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:parse_server_sdk/parse_server_sdk.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeParseCoreData extends _i1.Fake implements _i2.ParseCoreData {}

class _FakeParseNetworkResponse extends _i1.Fake
    implements _i2.ParseNetworkResponse {}

class _FakeParseNetworkByteResponse extends _i1.Fake
    implements _i2.ParseNetworkByteResponse {}

/// A class which mocks [ParseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockParseClient extends _i1.Mock implements _i2.ParseClient {
  MockParseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ParseCoreData get data => (super.noSuchMethod(Invocation.getter(#data),
      returnValue: _FakeParseCoreData()) as _i2.ParseCoreData);
  @override
  _i3.Future<_i2.ParseNetworkResponse> get(String? path,
          {_i2.ParseNetworkOptions? options,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#get, [path],
                  {#options: options, #onReceiveProgress: onReceiveProgress}),
              returnValue: Future<_i2.ParseNetworkResponse>.value(
                  _FakeParseNetworkResponse()))
          as _i3.Future<_i2.ParseNetworkResponse>);
  @override
  _i3.Future<_i2.ParseNetworkResponse> put(String? path,
          {String? data, _i2.ParseNetworkOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [path], {#data: data, #options: options}),
              returnValue: Future<_i2.ParseNetworkResponse>.value(
                  _FakeParseNetworkResponse()))
          as _i3.Future<_i2.ParseNetworkResponse>);
  @override
  _i3.Future<_i2.ParseNetworkResponse> post(String? path,
          {String? data, _i2.ParseNetworkOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(#post, [path], {#data: data, #options: options}),
          returnValue: Future<_i2.ParseNetworkResponse>.value(
              _FakeParseNetworkResponse())) as _i3
          .Future<_i2.ParseNetworkResponse>);
  @override
  _i3.Future<_i2.ParseNetworkResponse> postBytes(String? path,
          {_i3.Stream<List<int>>? data,
          _i2.ParseNetworkOptions? options,
          _i2.ProgressCallback? onSendProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#postBytes, [
                path
              ], {
                #data: data,
                #options: options,
                #onSendProgress: onSendProgress
              }),
              returnValue: Future<_i2.ParseNetworkResponse>.value(
                  _FakeParseNetworkResponse()))
          as _i3.Future<_i2.ParseNetworkResponse>);
  @override
  _i3.Future<_i2.ParseNetworkResponse> delete(String? path,
          {_i2.ParseNetworkOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [path], {#options: options}),
              returnValue: Future<_i2.ParseNetworkResponse>.value(
                  _FakeParseNetworkResponse()))
          as _i3.Future<_i2.ParseNetworkResponse>);
  @override
  _i3.Future<_i2.ParseNetworkByteResponse> getBytes(String? path,
          {_i2.ParseNetworkOptions? options,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#getBytes, [path],
                  {#options: options, #onReceiveProgress: onReceiveProgress}),
              returnValue: Future<_i2.ParseNetworkByteResponse>.value(
                  _FakeParseNetworkByteResponse()))
          as _i3.Future<_i2.ParseNetworkByteResponse>);
}
