name: release-manual-docs
on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        description: 'Version tag:' 
jobs:
  docs-publish:
    if: github.event.inputs.tag != ''
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Setup dart
        uses: dart-lang/setup-dart@v1
      - name: Generate Docs
        run: |
          dart doc ./packages/dart/ -o ./.api_docs/dart/
          dart doc ./packages/flutter/ -o ./.api_docs/flutter/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.api_docs/
