name: Test the packages
on:
  push:
    paths-ignore:
      - "**/README.md"
      - "docs/**"
  pull_request:

jobs:
  test-dart:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta, dev]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get --directory packages/dart

      - name: Run build_runner
        run: (cd packages/dart && dart run build_runner build --delete-conflicting-outputs)

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed packages/dart

      - name: Analyze project source
        run: dart analyze packages/dart

      - name: Run tests
        run: (cd packages/dart && dart test)

  test-flutter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable, beta]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: |
          (cd packages/dart && flutter pub get)
          cd packages/flutter
          flutter pub remove parse_server_sdk
          flutter pub add parse_server_sdk --path ../dart
          flutter pub get

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed packages/flutter

      - name: Analyze project source
        run: flutter analyze packages/flutter

      - name: Run tests
        run: (cd packages/flutter && flutter test)
